repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        exclude: ^(tests/.*)$
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        always_run: true
        args:
          [
            "--ignore=ANN101,ANN102,D200,D100,D101,D102,D103,D104,D107,I001,I005,I004,I003",
          ]
        exclude: ^(tests/.*)$
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        exclude: ^(tests/.*)$
      - id: pytest
        name: pytest
        entry: pytest
        args: ["--cov=src --cov-report=term --cov-branch -cov-fail-under=5"]
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
