repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args: [--check]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        always_run: true
        args: [--check]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        always_run: true
        args: [--check]

      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: [--check]

      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
