version: "3.8"

services:
  db-test:
    container_name: "postgres-test"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
  cache:
    container_name: "cache"
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - custom
networks:
  custom:
    driver: bridge
